<script lang="ts" setup>
// Fetch data using composables
const site = useSiteConfig()
const { data: profileData } = await useProfileData()

// SEO Meta using reactive composables
if (profileData.value) {
  // Trim description to ~155 chars for optimal SERP display
  const shortDescription =
    profileData.value.description.length > 155
      ? profileData.value.description.slice(0, 152) + "..."
      : profileData.value.description

  useSeoMeta({
    title: "Home",
    description: shortDescription,
    ogTitle: profileData.value.name,
    ogDescription: shortDescription,
    ogImage: profileData.value.avatar,
    ogType: "website",
    twitterCard: "summary_large_image",
    twitterTitle: profileData.value.name,
    twitterDescription: shortDescription,
    twitterImage: profileData.value.avatar,
  })

  // Structured data for SEO
  // Person and WebSite schemas are auto-generated by @nuxtjs/seo from site config + schemaOrg.identity
  useSchemaOrg([
    {
      "@type": "BreadcrumbList",
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: site.url,
        },
      ],
    },
  ])
}

definePageMeta({
  layout: "home",
})
</script>

<template>
  <UPage>
    <UPageHero
      v-if="profileData"
      orientation="horizontal"
      :ui="{
        root: 'relative isolate flex min-h-[calc(100svh-var(--ui-header-height))] flex-col',
        container: 'flex-1 py-16 sm:py-24 gap-12 justify-center',
      }"
    >
      <template #headline>
        <span class="font-mono text-sm text-primary">{{
          profileData.title
        }}</span>
      </template>
      <template #title>
        <span class="font-mono font-medium tracking-tight">
          {{ profileData.name }}
        </span>
      </template>
      <template #description>
        {{ profileData.heroHeadline }}
      </template>
      <template #links>
        <UButton
          v-for="social in profileData.social"
          :key="social.name"
          :to="social.url"
          external
          :title="social.name"
          variant="ghost"
          color="neutral"
          :icon="social.icon"
        />
      </template>

      <div class="w-full max-w-md">
        <UCard
          variant="outline"
          class="font-mono text-sm leading-relaxed"
          :ui="{
            header: 'px-4 py-2.5',
            body: 'p-4 sm:p-5',
          }"
        >
          <template #header>
            <div class="flex items-center gap-1.5">
              <span class="size-2.5 rounded-full bg-red-400/80" />
              <span class="size-2.5 rounded-full bg-yellow-400/80" />
              <span class="size-2.5 rounded-full bg-green-400/80" />
              <span class="ml-2 text-xs text-muted">~/mubaidr.md</span>
            </div>
          </template>
          {{ profileData.description }}
        </UCard>
      </div>
    </UPageHero>
    <UPageBody>
      <WhatIDo />
      <!-- <FeaturedProjects :hide-link="true" /> -->
      <FeaturedTestimonials />
      <RecentBlogPosts />
    </UPageBody>
  </UPage>
</template>
